#pragma once

#include "order_book.hpp"

#include <atomic>
#include <chrono>
#include <string>
#include <vector>
#include <memory>
#include <unordered_map>
#include <functional>
#include <optional>

// EngineStats
//
// Accumulated counters since the engine started (or since last reset).
// All fields are plain values — the engine updates them under its own
// single-threaded contract; no atomics needed here.

struct EngineStats {
    uint64_t orders_received  { 0 };
    uint64_t orders_filled    { 0 };   // fully filled
    uint64_t orders_partial   { 0 };   // resting with at least one fill
    uint64_t orders_cancelled { 0 };
    uint64_t orders_rejected  { 0 };
    uint64_t trades_executed  { 0 };
    Quantity total_volume     { 0 };   // shares / contracts traded

    // Latency tracking (nanoseconds).
    uint64_t total_latency_ns { 0 };
    uint64_t min_latency_ns   { UINT64_MAX };
    uint64_t max_latency_ns   { 0 };

    uint64_t avg_latency_ns() const;
    double   orders_per_second(double elapsed_seconds) const;

    void reset();
    void print() const;
};

// OrderResult
//
// What came back from a single submit_order() call.

struct OrderResult {
    OrderId            order_id;
    bool               accepted  { false };
    std::string        reject_reason;
    std::vector<Trade> trades;   // trades generated by this order, if any
};

// MatchingEngine
//
// Top-level entry point.  Owns a map of symbols → OrderBooks, a monotonic
// order-id counter, and the stats accumulator.
//
// Thread safety: NOT thread-safe by design.  For multi-threaded throughput,
// shard by symbol and give each shard its own engine instance.

class MatchingEngine {
public:
    using TradeCallback  = std::function<void(const std::string& symbol, const Trade&)>;
    using RejectCallback = std::function<void(OrderId, const std::string& reason)>;

    explicit MatchingEngine(TradeCallback  on_trade  = nullptr,
                            RejectCallback on_reject = nullptr);

    // Register a tradeable instrument.  Must be called before any orders
    // for that symbol are submitted.
    void add_symbol(const std::string& symbol);
    bool has_symbol(const std::string& symbol) const;

    // Core API

    // Build and submit a limit order.  Returns an OrderResult with the
    // generated id and any immediate fills.
    OrderResult submit_limit(const std::string& symbol,
                             Side               side,
                             Price              price,
                             Quantity           qty,
                             const std::string& trader_id = "");

    // Build and submit a market order.
    OrderResult submit_market(const std::string& symbol,
                              Side               side,
                              Quantity           qty,
                              const std::string& trader_id = "");

    // Cancel a resting order by id.  Returns false if not found or already done.
    bool cancel_order(const std::string& symbol, OrderId id);

    // Queries

    const OrderBook* book(const std::string& symbol) const;

    std::optional<Price> best_bid(const std::string& symbol) const;
    std::optional<Price> best_ask(const std::string& symbol) const;
    std::optional<Price> spread   (const std::string& symbol) const;

    // Stats & diagnostics

    const EngineStats& stats() const { return stats_; }
    void               reset_stats()  { stats_.reset(); }
    void               print_stats()  const { stats_.print(); }

    // Wraps OrderBook::print_top.
    void print_book(const std::string& symbol, std::size_t levels = 5) const;

    // Run a quick latency benchmark: submits N limit orders against each
    // other and reports throughput.
    void run_benchmark(const std::string& symbol, uint64_t num_orders = 100'000);

private:
    std::atomic<OrderId> next_id_ { 1 };

    std::unordered_map<std::string, std::unique_ptr<OrderBook>> books_;

    TradeCallback  on_trade_;
    RejectCallback on_reject_;

    EngineStats stats_;

    // Internal submit — both public variants funnel through here.
    OrderResult submit(const std::string& symbol, std::unique_ptr<Order> order);

    OrderBook* get_book(const std::string& symbol);
    const OrderBook* get_book(const std::string& symbol) const;

    void record_latency(uint64_t ns);
    void accumulate_trades(const std::vector<Trade>& trades);
};